// Контракт сервиса оценки analyzer-service (issue #2).
//
// analyzer-service рассчитывает окупаемость объявления-продажи по кластеру
// арендных студий того же ЖК/дома (методика #64/#55) и пишет результат в
// кэш ad_roi_results. Поля сообщений повторяют схему БД (миграции
// 000014/000015/000016) и структуры internal/evaluate.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: analyzer/v1/analyzer.proto

package analyzerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluateAdRequest — какое объявление оценить.
type EvaluateAdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id объявления (avito_listings.id).
	AdId          int64 `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAdRequest) Reset() {
	*x = EvaluateAdRequest{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAdRequest) ProtoMessage() {}

func (x *EvaluateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAdRequest.ProtoReflect.Descriptor instead.
func (*EvaluateAdRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateAdRequest) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

// AnalysisResult — результат оценки окупаемости (тело ad_roi_results).
// Пустые сценарии с applicable=false соответствуют NULL-колонкам в БД
// («сценарий неприменим или нет арендных данных», не ноль).
type AnalysisResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id объявления (ad_roi_results.ad_id).
	AdId int64 `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	// Статус расчёта: ok | no_rent_data (ad_roi_results.status).
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Меблировка входного объявления (input_furnishing):
	// furnished | unfurnished | unknown.
	Furnishing string `protobuf:"bytes,3,opt,name=furnishing,proto3" json:"furnishing,omitempty"`
	// Сценарий «без мебели» (колонки *_unfurnished).
	Unfurnished *Scenario `protobuf:"bytes,4,opt,name=unfurnished,proto3" json:"unfurnished,omitempty"`
	// Сценарий «с мебелью» (колонки *_furnished).
	Furnished *Scenario `protobuf:"bytes,5,opt,name=furnished,proto3" json:"furnished,omitempty"`
	// Комиссия риэлтора (realtor_fee).
	RealtorFee int64 `protobuf:"varint,6,opt,name=realtor_fee,json=realtorFee,proto3" json:"realtor_fee,omitempty"`
	// Титульное страхование и оформление (deal_costs_other).
	DealCostsOther int64 `protobuf:"varint,7,opt,name=deal_costs_other,json=dealCostsOther,proto3" json:"deal_costs_other,omitempty"`
	// Полные издержки сделки (deal_costs_total).
	DealCostsTotal int64 `protobuf:"varint,8,opt,name=deal_costs_total,json=dealCostsTotal,proto3" json:"deal_costs_total,omitempty"`
	// Размер арендного кластера (cluster_n).
	ClusterN int32 `protobuf:"varint,9,opt,name=cluster_n,json=clusterN,proto3" json:"cluster_n,omitempty"`
	// Достоверность по размеру кластера (confidence): high | medium | low.
	Confidence string `protobuf:"bytes,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Человекочитаемая сноска методики (notice).
	Notice string `protobuf:"bytes,11,opt,name=notice,proto3" json:"notice,omitempty"`
	// Момент расчёта (computed_at).
	ComputedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResult) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *AnalysisResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResult) GetFurnishing() string {
	if x != nil {
		return x.Furnishing
	}
	return ""
}

func (x *AnalysisResult) GetUnfurnished() *Scenario {
	if x != nil {
		return x.Unfurnished
	}
	return nil
}

func (x *AnalysisResult) GetFurnished() *Scenario {
	if x != nil {
		return x.Furnished
	}
	return nil
}

func (x *AnalysisResult) GetRealtorFee() int64 {
	if x != nil {
		return x.RealtorFee
	}
	return 0
}

func (x *AnalysisResult) GetDealCostsOther() int64 {
	if x != nil {
		return x.DealCostsOther
	}
	return 0
}

func (x *AnalysisResult) GetDealCostsTotal() int64 {
	if x != nil {
		return x.DealCostsTotal
	}
	return 0
}

func (x *AnalysisResult) GetClusterN() int32 {
	if x != nil {
		return x.ClusterN
	}
	return 0
}

func (x *AnalysisResult) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *AnalysisResult) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *AnalysisResult) GetComputedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ComputedAt
	}
	return nil
}

// Scenario — один сценарий окупаемости (пара колонок *_unfurnished /
// *_furnished таблицы ad_roi_results; арифметика evaluate.Scenario).
type Scenario struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// false — сценарий неприменим (нет арендных данных), в БД NULL.
	Applicable bool `protobuf:"varint,1,opt,name=applicable,proto3" json:"applicable,omitempty"`
	// Медиана аренды кластера, ₽/мес (rent_median_*).
	RentMedian float64 `protobuf:"fixed64,2,opt,name=rent_median,json=rentMedian,proto3" json:"rent_median,omitempty"`
	// Ожидаемая аренда p25 (rent_p25_*).
	RentP25 float64 `protobuf:"fixed64,3,opt,name=rent_p25,json=rentP25,proto3" json:"rent_p25,omitempty"`
	// Ожидаемая аренда p75 (rent_p75_*).
	RentP75 float64 `protobuf:"fixed64,4,opt,name=rent_p75,json=rentP75,proto3" json:"rent_p75,omitempty"`
	// Число аналогов сценария (comps_*).
	Comps int32 `protobuf:"varint,5,opt,name=comps,proto3" json:"comps,omitempty"`
	// Доходность, % в год (yield_*_pct).
	YieldPct float64 `protobuf:"fixed64,6,opt,name=yield_pct,json=yieldPct,proto3" json:"yield_pct,omitempty"`
	// Окупаемость, лет: full_cost / (rent_median × 12) (payback_years).
	PaybackYears float64 `protobuf:"fixed64,7,opt,name=payback_years,json=paybackYears,proto3" json:"payback_years,omitempty"`
	// Полная стоимость сделки: цена + меблировка + издержки (total_cost_*).
	FullCost int64 `protobuf:"varint,8,opt,name=full_cost,json=fullCost,proto3" json:"full_cost,omitempty"`
	// Надбавка на меблировку (furnishing_cost; 0 — не применялась).
	FurnishingCost int64 `protobuf:"varint,9,opt,name=furnishing_cost,json=furnishingCost,proto3" json:"furnishing_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *Scenario) GetApplicable() bool {
	if x != nil {
		return x.Applicable
	}
	return false
}

func (x *Scenario) GetRentMedian() float64 {
	if x != nil {
		return x.RentMedian
	}
	return 0
}

func (x *Scenario) GetRentP25() float64 {
	if x != nil {
		return x.RentP25
	}
	return 0
}

func (x *Scenario) GetRentP75() float64 {
	if x != nil {
		return x.RentP75
	}
	return 0
}

func (x *Scenario) GetComps() int32 {
	if x != nil {
		return x.Comps
	}
	return 0
}

func (x *Scenario) GetYieldPct() float64 {
	if x != nil {
		return x.YieldPct
	}
	return 0
}

func (x *Scenario) GetPaybackYears() float64 {
	if x != nil {
		return x.PaybackYears
	}
	return 0
}

func (x *Scenario) GetFullCost() int64 {
	if x != nil {
		return x.FullCost
	}
	return 0
}

func (x *Scenario) GetFurnishingCost() int64 {
	if x != nil {
		return x.FurnishingCost
	}
	return 0
}

// UpdateAnalysisRequest — результат оценки для записи в кэш.
type UpdateAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *AnalysisResult        `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnalysisRequest) Reset() {
	*x = UpdateAnalysisRequest{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnalysisRequest) ProtoMessage() {}

func (x *UpdateAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnalysisRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAnalysisRequest) GetAnalysis() *AnalysisResult {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// UpdateAnalysisResponse — подтверждение записи.
type UpdateAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnalysisResponse) Reset() {
	*x = UpdateAnalysisResponse{}
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnalysisResponse) ProtoMessage() {}

func (x *UpdateAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analyzer_v1_analyzer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnalysisResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analyzer_v1_analyzer_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAnalysisResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_analyzer_v1_analyzer_proto protoreflect.FileDescriptor

const file_analyzer_v1_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x1aanalyzer/v1/analyzer.proto\x12\vanalyzer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x11EvaluateAdRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\"\xd2\x03\n" +
	"\x0eAnalysisResult\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"furnishing\x18\x03 \x01(\tR\n" +
	"furnishing\x127\n" +
	"\vunfurnished\x18\x04 \x01(\v2\x15.analyzer.v1.ScenarioR\vunfurnished\x123\n" +
	"\tfurnished\x18\x05 \x01(\v2\x15.analyzer.v1.ScenarioR\tfurnished\x12\x1f\n" +
	"\vrealtor_fee\x18\x06 \x01(\x03R\n" +
	"realtorFee\x12(\n" +
	"\x10deal_costs_other\x18\a \x01(\x03R\x0edealCostsOther\x12(\n" +
	"\x10deal_costs_total\x18\b \x01(\x03R\x0edealCostsTotal\x12\x1b\n" +
	"\tcluster_n\x18\t \x01(\x05R\bclusterN\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\tR\n" +
	"confidence\x12\x16\n" +
	"\x06notice\x18\v \x01(\tR\x06notice\x12;\n" +
	"\vcomputed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"computedAt\"\x9f\x02\n" +
	"\bScenario\x12\x1e\n" +
	"\n" +
	"applicable\x18\x01 \x01(\bR\n" +
	"applicable\x12\x1f\n" +
	"\vrent_median\x18\x02 \x01(\x01R\n" +
	"rentMedian\x12\x19\n" +
	"\brent_p25\x18\x03 \x01(\x01R\arentP25\x12\x19\n" +
	"\brent_p75\x18\x04 \x01(\x01R\arentP75\x12\x14\n" +
	"\x05comps\x18\x05 \x01(\x05R\x05comps\x12\x1b\n" +
	"\tyield_pct\x18\x06 \x01(\x01R\byieldPct\x12#\n" +
	"\rpayback_years\x18\a \x01(\x01R\fpaybackYears\x12\x1b\n" +
	"\tfull_cost\x18\b \x01(\x03R\bfullCost\x12'\n" +
	"\x0ffurnishing_cost\x18\t \x01(\x03R\x0efurnishingCost\"P\n" +
	"\x15UpdateAnalysisRequest\x127\n" +
	"\banalysis\x18\x01 \x01(\v2\x1b.analyzer.v1.AnalysisResultR\banalysis\"(\n" +
	"\x16UpdateAnalysisResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xb7\x01\n" +
	"\x0fAnalyzerService\x12I\n" +
	"\n" +
	"EvaluateAd\x12\x1e.analyzer.v1.EvaluateAdRequest\x1a\x1b.analyzer.v1.AnalysisResult\x12Y\n" +
	"\x0eUpdateAnalysis\x12\".analyzer.v1.UpdateAnalysisRequest\x1a#.analyzer.v1.UpdateAnalysisResponseBOZMgithub.com/yourusername/real-estate-analyzer/pkg/proto/analyzer/v1;analyzerv1b\x06proto3"

var (
	file_analyzer_v1_analyzer_proto_rawDescOnce sync.Once
	file_analyzer_v1_analyzer_proto_rawDescData []byte
)

func file_analyzer_v1_analyzer_proto_rawDescGZIP() []byte {
	file_analyzer_v1_analyzer_proto_rawDescOnce.Do(func() {
		file_analyzer_v1_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyzer_v1_analyzer_proto_rawDesc), len(file_analyzer_v1_analyzer_proto_rawDesc)))
	})
	return file_analyzer_v1_analyzer_proto_rawDescData
}

var file_analyzer_v1_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analyzer_v1_analyzer_proto_goTypes = []any{
	(*EvaluateAdRequest)(nil),      // 0: analyzer.v1.EvaluateAdRequest
	(*AnalysisResult)(nil),         // 1: analyzer.v1.AnalysisResult
	(*Scenario)(nil),               // 2: analyzer.v1.Scenario
	(*UpdateAnalysisRequest)(nil),  // 3: analyzer.v1.UpdateAnalysisRequest
	(*UpdateAnalysisResponse)(nil), // 4: analyzer.v1.UpdateAnalysisResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_analyzer_v1_analyzer_proto_depIdxs = []int32{
	2, // 0: analyzer.v1.AnalysisResult.unfurnished:type_name -> analyzer.v1.Scenario
	2, // 1: analyzer.v1.AnalysisResult.furnished:type_name -> analyzer.v1.Scenario
	5, // 2: analyzer.v1.AnalysisResult.computed_at:type_name -> google.protobuf.Timestamp
	1, // 3: analyzer.v1.UpdateAnalysisRequest.analysis:type_name -> analyzer.v1.AnalysisResult
	0, // 4: analyzer.v1.AnalyzerService.EvaluateAd:input_type -> analyzer.v1.EvaluateAdRequest
	3, // 5: analyzer.v1.AnalyzerService.UpdateAnalysis:input_type -> analyzer.v1.UpdateAnalysisRequest
	1, // 6: analyzer.v1.AnalyzerService.EvaluateAd:output_type -> analyzer.v1.AnalysisResult
	4, // 7: analyzer.v1.AnalyzerService.UpdateAnalysis:output_type -> analyzer.v1.UpdateAnalysisResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_analyzer_v1_analyzer_proto_init() }
func file_analyzer_v1_analyzer_proto_init() {
	if File_analyzer_v1_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyzer_v1_analyzer_proto_rawDesc), len(file_analyzer_v1_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analyzer_v1_analyzer_proto_goTypes,
		DependencyIndexes: file_analyzer_v1_analyzer_proto_depIdxs,
		MessageInfos:      file_analyzer_v1_analyzer_proto_msgTypes,
	}.Build()
	File_analyzer_v1_analyzer_proto = out.File
	file_analyzer_v1_analyzer_proto_goTypes = nil
	file_analyzer_v1_analyzer_proto_depIdxs = nil
}
