// Контракт сервиса оценки analyzer-service (issue #2).
//
// analyzer-service рассчитывает окупаемость объявления-продажи по кластеру
// арендных студий того же ЖК/дома (методика #64/#55) и пишет результат в
// кэш ad_roi_results. Поля сообщений повторяют схему БД (миграции
// 000014/000015/000016) и структуры internal/evaluate.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: analyzer/v1/analyzer.proto

package analyzerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyzerService_EvaluateAd_FullMethodName     = "/analyzer.v1.AnalyzerService/EvaluateAd"
	AnalyzerService_UpdateAnalysis_FullMethodName = "/analyzer.v1.AnalyzerService/UpdateAnalysis"
)

// AnalyzerServiceClient is the client API for AnalyzerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalyzerService — расчёт и обновление результатов оценки.
type AnalyzerServiceClient interface {
	// EvaluateAd — рассчитать оценку объявления-продажи по id
	// (avito_listings.id).
	EvaluateAd(ctx context.Context, in *EvaluateAdRequest, opts ...grpc.CallOption) (*AnalysisResult, error)
	// UpdateAnalysis — записать готовый результат оценки в кэш
	// (analysis_results / таблица ad_roi_results).
	UpdateAnalysis(ctx context.Context, in *UpdateAnalysisRequest, opts ...grpc.CallOption) (*UpdateAnalysisResponse, error)
}

type analyzerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyzerServiceClient(cc grpc.ClientConnInterface) AnalyzerServiceClient {
	return &analyzerServiceClient{cc}
}

func (c *analyzerServiceClient) EvaluateAd(ctx context.Context, in *EvaluateAdRequest, opts ...grpc.CallOption) (*AnalysisResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResult)
	err := c.cc.Invoke(ctx, AnalyzerService_EvaluateAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyzerServiceClient) UpdateAnalysis(ctx context.Context, in *UpdateAnalysisRequest, opts ...grpc.CallOption) (*UpdateAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAnalysisResponse)
	err := c.cc.Invoke(ctx, AnalyzerService_UpdateAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyzerServiceServer is the server API for AnalyzerService service.
// All implementations must embed UnimplementedAnalyzerServiceServer
// for forward compatibility.
//
// AnalyzerService — расчёт и обновление результатов оценки.
type AnalyzerServiceServer interface {
	// EvaluateAd — рассчитать оценку объявления-продажи по id
	// (avito_listings.id).
	EvaluateAd(context.Context, *EvaluateAdRequest) (*AnalysisResult, error)
	// UpdateAnalysis — записать готовый результат оценки в кэш
	// (analysis_results / таблица ad_roi_results).
	UpdateAnalysis(context.Context, *UpdateAnalysisRequest) (*UpdateAnalysisResponse, error)
	mustEmbedUnimplementedAnalyzerServiceServer()
}

// UnimplementedAnalyzerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyzerServiceServer struct{}

func (UnimplementedAnalyzerServiceServer) EvaluateAd(context.Context, *EvaluateAdRequest) (*AnalysisResult, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateAd not implemented")
}
func (UnimplementedAnalyzerServiceServer) UpdateAnalysis(context.Context, *UpdateAnalysisRequest) (*UpdateAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAnalysis not implemented")
}
func (UnimplementedAnalyzerServiceServer) mustEmbedUnimplementedAnalyzerServiceServer() {}
func (UnimplementedAnalyzerServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalyzerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyzerServiceServer will
// result in compilation errors.
type UnsafeAnalyzerServiceServer interface {
	mustEmbedUnimplementedAnalyzerServiceServer()
}

func RegisterAnalyzerServiceServer(s grpc.ServiceRegistrar, srv AnalyzerServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyzerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyzerService_ServiceDesc, srv)
}

func _AnalyzerService_EvaluateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).EvaluateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_EvaluateAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).EvaluateAd(ctx, req.(*EvaluateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyzerService_UpdateAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyzerServiceServer).UpdateAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyzerService_UpdateAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyzerServiceServer).UpdateAnalysis(ctx, req.(*UpdateAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyzerService_ServiceDesc is the grpc.ServiceDesc for AnalyzerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyzerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analyzer.v1.AnalyzerService",
	HandlerType: (*AnalyzerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateAd",
			Handler:    _AnalyzerService_EvaluateAd_Handler,
		},
		{
			MethodName: "UpdateAnalysis",
			Handler:    _AnalyzerService_UpdateAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analyzer/v1/analyzer.proto",
}
