// Контракт сервиса объявлений ads-service (issue #2).
//
// MVP-поток: parser-service сохраняет объявление через CreateAd,
// analyzer-service записывает результат оценки через UpdateAnalysis,
// клиенты читают объявление (GetAd) и похожие объекты того же ЖК
// (GetSimilarAds). Поля сообщения Ad повторяют схему avito_listings
// (миграции 000010 и 000011).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ads/v1/ads.proto

package adsv1

import (
	v1 "github.com/yourusername/real-estate-analyzer/pkg/proto/analyzer/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ad — объявление недвижимости (срез avito_listings, достаточный для
// MVP-потока и карточки объекта).
type Ad struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id объявления на Авито (первичный ключ avito_listings).
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Полный URL карточки (https://www.avito.ru{url_path}).
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Путь карточки (/moskva/kvartiry/1-k._kvartira_..._1234567890).
	UrlPath string `protobuf:"bytes,3,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	// Заголовок объявления.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Тип сделки (deal_type): sale | rent_long | rent_daily.
	DealType string `protobuf:"bytes,5,opt,name=deal_type,json=dealType,proto3" json:"deal_type,omitempty"`
	// Категория (category): kvartiry | komnaty | ... .
	Category string `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	// Цена, ₽ целым числом (price).
	Price int64 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	// Число комнат; 0 у студий, отсутствие — optional (rooms).
	Rooms *int32 `protobuf:"varint,8,opt,name=rooms,proto3,oneof" json:"rooms,omitempty"`
	// Признак студии (studio).
	Studio bool `protobuf:"varint,9,opt,name=studio,proto3" json:"studio,omitempty"`
	// Общая площадь, м2 (total_area).
	TotalArea *float64 `protobuf:"fixed64,10,opt,name=total_area,json=totalArea,proto3,oneof" json:"total_area,omitempty"`
	// Этаж (floor).
	Floor *int32 `protobuf:"varint,11,opt,name=floor,proto3,oneof" json:"floor,omitempty"`
	// Этажность дома (floors_total).
	FloorsTotal *int32 `protobuf:"varint,12,opt,name=floors_total,json=floorsTotal,proto3,oneof" json:"floors_total,omitempty"`
	// Человекочитаемый адрес (address).
	Address string `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	// Город (city).
	City string `protobuf:"bytes,14,opt,name=city,proto3" json:"city,omitempty"`
	// Район (district).
	District string `protobuf:"bytes,15,opt,name=district,proto3" json:"district,omitempty"`
	// Станция метро (metro).
	Metro string `protobuf:"bytes,16,opt,name=metro,proto3" json:"metro,omitempty"`
	// Название ЖК (residential_complex, миграция 000011).
	ResidentialComplex string `protobuf:"bytes,17,opt,name=residential_complex,json=residentialComplex,proto3" json:"residential_complex,omitempty"`
	// Широта (lat).
	Lat *float64 `protobuf:"fixed64,18,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	// Долгота (lng).
	Lng *float64 `protobuf:"fixed64,19,opt,name=lng,proto3,oneof" json:"lng,omitempty"`
	// Фотографии (images JSONB в БД).
	Photos []*Photo `protobuf:"bytes,20,rep,name=photos,proto3" json:"photos,omitempty"`
	// Описание объявления (description; по нему анализируется меблировка).
	Description   string `protobuf:"bytes,21,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_ads_v1_ads_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ad) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Ad) GetUrlPath() string {
	if x != nil {
		return x.UrlPath
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDealType() string {
	if x != nil {
		return x.DealType
	}
	return ""
}

func (x *Ad) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Ad) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ad) GetRooms() int32 {
	if x != nil && x.Rooms != nil {
		return *x.Rooms
	}
	return 0
}

func (x *Ad) GetStudio() bool {
	if x != nil {
		return x.Studio
	}
	return false
}

func (x *Ad) GetTotalArea() float64 {
	if x != nil && x.TotalArea != nil {
		return *x.TotalArea
	}
	return 0
}

func (x *Ad) GetFloor() int32 {
	if x != nil && x.Floor != nil {
		return *x.Floor
	}
	return 0
}

func (x *Ad) GetFloorsTotal() int32 {
	if x != nil && x.FloorsTotal != nil {
		return *x.FloorsTotal
	}
	return 0
}

func (x *Ad) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Ad) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Ad) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *Ad) GetMetro() string {
	if x != nil {
		return x.Metro
	}
	return ""
}

func (x *Ad) GetResidentialComplex() string {
	if x != nil {
		return x.ResidentialComplex
	}
	return ""
}

func (x *Ad) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Ad) GetLng() float64 {
	if x != nil && x.Lng != nil {
		return *x.Lng
	}
	return 0
}

func (x *Ad) GetPhotos() []*Photo {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Photo — фотография объявления (элемент images в avito_listings).
type Photo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Photo) Reset() {
	*x = Photo{}
	mi := &file_ads_v1_ads_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{1}
}

func (x *Photo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Photo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Photo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// GetAdRequest — id объявления.
type GetAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdRequest) Reset() {
	*x = GetAdRequest{}
	mi := &file_ads_v1_ads_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdRequest) ProtoMessage() {}

func (x *GetAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdRequest.ProtoReflect.Descriptor instead.
func (*GetAdRequest) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CreateAdRequest — объявление для сохранения (upsert по Ad.id).
type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_ads_v1_ads_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAdRequest) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

// CreateAdResponse — id сохранённого объявления и признак создания.
type CreateAdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// true — объявление создано, false — обновлено существующее.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_ads_v1_ads_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAdResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// UpdateAnalysisRequest — результат оценки для привязки к объявлению.
type UpdateAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analysis      *v1.AnalysisResult     `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnalysisRequest) Reset() {
	*x = UpdateAnalysisRequest{}
	mi := &file_ads_v1_ads_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnalysisRequest) ProtoMessage() {}

func (x *UpdateAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnalysisRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAnalysisRequest) GetAnalysis() *v1.AnalysisResult {
	if x != nil {
		return x.Analysis
	}
	return nil
}

// UpdateAnalysisResponse — подтверждение записи.
type UpdateAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnalysisResponse) Reset() {
	*x = UpdateAnalysisResponse{}
	mi := &file_ads_v1_ads_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnalysisResponse) ProtoMessage() {}

func (x *UpdateAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnalysisResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAnalysisResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// GetSimilarAdsRequest — похожие для объявления.
type GetSimilarAdsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id исходного объявления.
	AdId int64 `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	// Максимум объявлений в ответе (лимит по умолчанию — на стороне сервиса).
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarAdsRequest) Reset() {
	*x = GetSimilarAdsRequest{}
	mi := &file_ads_v1_ads_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarAdsRequest) ProtoMessage() {}

func (x *GetSimilarAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarAdsRequest.ProtoReflect.Descriptor instead.
func (*GetSimilarAdsRequest) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{7}
}

func (x *GetSimilarAdsRequest) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *GetSimilarAdsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetSimilarAdsResponse — похожие объявления (кластер того же ЖК/дома).
type GetSimilarAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*Ad                  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimilarAdsResponse) Reset() {
	*x = GetSimilarAdsResponse{}
	mi := &file_ads_v1_ads_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimilarAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimilarAdsResponse) ProtoMessage() {}

func (x *GetSimilarAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ads_v1_ads_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimilarAdsResponse.ProtoReflect.Descriptor instead.
func (*GetSimilarAdsResponse) Descriptor() ([]byte, []int) {
	return file_ads_v1_ads_proto_rawDescGZIP(), []int{8}
}

func (x *GetSimilarAdsResponse) GetAds() []*Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

var File_ads_v1_ads_proto protoreflect.FileDescriptor

const file_ads_v1_ads_proto_rawDesc = "" +
	"\n" +
	"\x10ads/v1/ads.proto\x12\x06ads.v1\x1a\x1aanalyzer/v1/analyzer.proto\"\x8c\x05\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\burl_path\x18\x03 \x01(\tR\aurlPath\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\tdeal_type\x18\x05 \x01(\tR\bdealType\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\a \x01(\x03R\x05price\x12\x19\n" +
	"\x05rooms\x18\b \x01(\x05H\x00R\x05rooms\x88\x01\x01\x12\x16\n" +
	"\x06studio\x18\t \x01(\bR\x06studio\x12\"\n" +
	"\n" +
	"total_area\x18\n" +
	" \x01(\x01H\x01R\ttotalArea\x88\x01\x01\x12\x19\n" +
	"\x05floor\x18\v \x01(\x05H\x02R\x05floor\x88\x01\x01\x12&\n" +
	"\ffloors_total\x18\f \x01(\x05H\x03R\vfloorsTotal\x88\x01\x01\x12\x18\n" +
	"\aaddress\x18\r \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x0e \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x0f \x01(\tR\bdistrict\x12\x14\n" +
	"\x05metro\x18\x10 \x01(\tR\x05metro\x12/\n" +
	"\x13residential_complex\x18\x11 \x01(\tR\x12residentialComplex\x12\x15\n" +
	"\x03lat\x18\x12 \x01(\x01H\x04R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lng\x18\x13 \x01(\x01H\x05R\x03lng\x88\x01\x01\x12%\n" +
	"\x06photos\x18\x14 \x03(\v2\r.ads.v1.PhotoR\x06photos\x12 \n" +
	"\vdescription\x18\x15 \x01(\tR\vdescriptionB\b\n" +
	"\x06_roomsB\r\n" +
	"\v_total_areaB\b\n" +
	"\x06_floorB\x0f\n" +
	"\r_floors_totalB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lng\"G\n" +
	"\x05Photo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\"\x1e\n" +
	"\fGetAdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"-\n" +
	"\x0fCreateAdRequest\x12\x1a\n" +
	"\x02ad\x18\x01 \x01(\v2\n" +
	".ads.v1.AdR\x02ad\"<\n" +
	"\x10CreateAdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"P\n" +
	"\x15UpdateAnalysisRequest\x127\n" +
	"\banalysis\x18\x01 \x01(\v2\x1b.analyzer.v1.AnalysisResultR\banalysis\"(\n" +
	"\x16UpdateAnalysisResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"A\n" +
	"\x14GetSimilarAdsRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"5\n" +
	"\x15GetSimilarAdsResponse\x12\x1c\n" +
	"\x03ads\x18\x01 \x03(\v2\n" +
	".ads.v1.AdR\x03ads2\x95\x02\n" +
	"\n" +
	"AdsService\x12)\n" +
	"\x05GetAd\x12\x14.ads.v1.GetAdRequest\x1a\n" +
	".ads.v1.Ad\x12=\n" +
	"\bCreateAd\x12\x17.ads.v1.CreateAdRequest\x1a\x18.ads.v1.CreateAdResponse\x12O\n" +
	"\x0eUpdateAnalysis\x12\x1d.ads.v1.UpdateAnalysisRequest\x1a\x1e.ads.v1.UpdateAnalysisResponse\x12L\n" +
	"\rGetSimilarAds\x12\x1c.ads.v1.GetSimilarAdsRequest\x1a\x1d.ads.v1.GetSimilarAdsResponseBEZCgithub.com/yourusername/real-estate-analyzer/pkg/proto/ads/v1;adsv1b\x06proto3"

var (
	file_ads_v1_ads_proto_rawDescOnce sync.Once
	file_ads_v1_ads_proto_rawDescData []byte
)

func file_ads_v1_ads_proto_rawDescGZIP() []byte {
	file_ads_v1_ads_proto_rawDescOnce.Do(func() {
		file_ads_v1_ads_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ads_v1_ads_proto_rawDesc), len(file_ads_v1_ads_proto_rawDesc)))
	})
	return file_ads_v1_ads_proto_rawDescData
}

var file_ads_v1_ads_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ads_v1_ads_proto_goTypes = []any{
	(*Ad)(nil),                     // 0: ads.v1.Ad
	(*Photo)(nil),                  // 1: ads.v1.Photo
	(*GetAdRequest)(nil),           // 2: ads.v1.GetAdRequest
	(*CreateAdRequest)(nil),        // 3: ads.v1.CreateAdRequest
	(*CreateAdResponse)(nil),       // 4: ads.v1.CreateAdResponse
	(*UpdateAnalysisRequest)(nil),  // 5: ads.v1.UpdateAnalysisRequest
	(*UpdateAnalysisResponse)(nil), // 6: ads.v1.UpdateAnalysisResponse
	(*GetSimilarAdsRequest)(nil),   // 7: ads.v1.GetSimilarAdsRequest
	(*GetSimilarAdsResponse)(nil),  // 8: ads.v1.GetSimilarAdsResponse
	(*v1.AnalysisResult)(nil),      // 9: analyzer.v1.AnalysisResult
}
var file_ads_v1_ads_proto_depIdxs = []int32{
	1, // 0: ads.v1.Ad.photos:type_name -> ads.v1.Photo
	0, // 1: ads.v1.CreateAdRequest.ad:type_name -> ads.v1.Ad
	9, // 2: ads.v1.UpdateAnalysisRequest.analysis:type_name -> analyzer.v1.AnalysisResult
	0, // 3: ads.v1.GetSimilarAdsResponse.ads:type_name -> ads.v1.Ad
	2, // 4: ads.v1.AdsService.GetAd:input_type -> ads.v1.GetAdRequest
	3, // 5: ads.v1.AdsService.CreateAd:input_type -> ads.v1.CreateAdRequest
	5, // 6: ads.v1.AdsService.UpdateAnalysis:input_type -> ads.v1.UpdateAnalysisRequest
	7, // 7: ads.v1.AdsService.GetSimilarAds:input_type -> ads.v1.GetSimilarAdsRequest
	0, // 8: ads.v1.AdsService.GetAd:output_type -> ads.v1.Ad
	4, // 9: ads.v1.AdsService.CreateAd:output_type -> ads.v1.CreateAdResponse
	6, // 10: ads.v1.AdsService.UpdateAnalysis:output_type -> ads.v1.UpdateAnalysisResponse
	8, // 11: ads.v1.AdsService.GetSimilarAds:output_type -> ads.v1.GetSimilarAdsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ads_v1_ads_proto_init() }
func file_ads_v1_ads_proto_init() {
	if File_ads_v1_ads_proto != nil {
		return
	}
	file_ads_v1_ads_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ads_v1_ads_proto_rawDesc), len(file_ads_v1_ads_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ads_v1_ads_proto_goTypes,
		DependencyIndexes: file_ads_v1_ads_proto_depIdxs,
		MessageInfos:      file_ads_v1_ads_proto_msgTypes,
	}.Build()
	File_ads_v1_ads_proto = out.File
	file_ads_v1_ads_proto_goTypes = nil
	file_ads_v1_ads_proto_depIdxs = nil
}
