// Контракт сервиса объявлений ads-service (issue #2).
//
// MVP-поток: parser-service сохраняет объявление через CreateAd,
// analyzer-service записывает результат оценки через UpdateAnalysis,
// клиенты читают объявление (GetAd) и похожие объекты того же ЖК
// (GetSimilarAds). Поля сообщения Ad повторяют схему avito_listings
// (миграции 000010 и 000011).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: ads/v1/ads.proto

package adsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdsService_GetAd_FullMethodName          = "/ads.v1.AdsService/GetAd"
	AdsService_CreateAd_FullMethodName       = "/ads.v1.AdsService/CreateAd"
	AdsService_UpdateAnalysis_FullMethodName = "/ads.v1.AdsService/UpdateAnalysis"
	AdsService_GetSimilarAds_FullMethodName  = "/ads.v1.AdsService/GetSimilarAds"
)

// AdsServiceClient is the client API for AdsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdsService — хранение объявлений и их результатов оценки.
type AdsServiceClient interface {
	// GetAd — объявление по id (avito_listings.id).
	GetAd(ctx context.Context, in *GetAdRequest, opts ...grpc.CallOption) (*Ad, error)
	// CreateAd — создать/обновить объявление (результат парсинга; upsert
	// по id, как в avito_listings).
	CreateAd(ctx context.Context, in *CreateAdRequest, opts ...grpc.CallOption) (*CreateAdResponse, error)
	// UpdateAnalysis — сохранить результат оценки объявления (кэш
	// ad_roi_results; считает analyzer-service).
	UpdateAnalysis(ctx context.Context, in *UpdateAnalysisRequest, opts ...grpc.CallOption) (*UpdateAnalysisResponse, error)
	// GetSimilarAds — похожие объявления (кластер того же ЖК/дома).
	GetSimilarAds(ctx context.Context, in *GetSimilarAdsRequest, opts ...grpc.CallOption) (*GetSimilarAdsResponse, error)
}

type adsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdsServiceClient(cc grpc.ClientConnInterface) AdsServiceClient {
	return &adsServiceClient{cc}
}

func (c *adsServiceClient) GetAd(ctx context.Context, in *GetAdRequest, opts ...grpc.CallOption) (*Ad, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ad)
	err := c.cc.Invoke(ctx, AdsService_GetAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) CreateAd(ctx context.Context, in *CreateAdRequest, opts ...grpc.CallOption) (*CreateAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdResponse)
	err := c.cc.Invoke(ctx, AdsService_CreateAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) UpdateAnalysis(ctx context.Context, in *UpdateAnalysisRequest, opts ...grpc.CallOption) (*UpdateAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAnalysisResponse)
	err := c.cc.Invoke(ctx, AdsService_UpdateAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adsServiceClient) GetSimilarAds(ctx context.Context, in *GetSimilarAdsRequest, opts ...grpc.CallOption) (*GetSimilarAdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimilarAdsResponse)
	err := c.cc.Invoke(ctx, AdsService_GetSimilarAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdsServiceServer is the server API for AdsService service.
// All implementations must embed UnimplementedAdsServiceServer
// for forward compatibility.
//
// AdsService — хранение объявлений и их результатов оценки.
type AdsServiceServer interface {
	// GetAd — объявление по id (avito_listings.id).
	GetAd(context.Context, *GetAdRequest) (*Ad, error)
	// CreateAd — создать/обновить объявление (результат парсинга; upsert
	// по id, как в avito_listings).
	CreateAd(context.Context, *CreateAdRequest) (*CreateAdResponse, error)
	// UpdateAnalysis — сохранить результат оценки объявления (кэш
	// ad_roi_results; считает analyzer-service).
	UpdateAnalysis(context.Context, *UpdateAnalysisRequest) (*UpdateAnalysisResponse, error)
	// GetSimilarAds — похожие объявления (кластер того же ЖК/дома).
	GetSimilarAds(context.Context, *GetSimilarAdsRequest) (*GetSimilarAdsResponse, error)
	mustEmbedUnimplementedAdsServiceServer()
}

// UnimplementedAdsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdsServiceServer struct{}

func (UnimplementedAdsServiceServer) GetAd(context.Context, *GetAdRequest) (*Ad, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAd not implemented")
}
func (UnimplementedAdsServiceServer) CreateAd(context.Context, *CreateAdRequest) (*CreateAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAd not implemented")
}
func (UnimplementedAdsServiceServer) UpdateAnalysis(context.Context, *UpdateAnalysisRequest) (*UpdateAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAnalysis not implemented")
}
func (UnimplementedAdsServiceServer) GetSimilarAds(context.Context, *GetSimilarAdsRequest) (*GetSimilarAdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSimilarAds not implemented")
}
func (UnimplementedAdsServiceServer) mustEmbedUnimplementedAdsServiceServer() {}
func (UnimplementedAdsServiceServer) testEmbeddedByValue()                    {}

// UnsafeAdsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdsServiceServer will
// result in compilation errors.
type UnsafeAdsServiceServer interface {
	mustEmbedUnimplementedAdsServiceServer()
}

func RegisterAdsServiceServer(s grpc.ServiceRegistrar, srv AdsServiceServer) {
	// If the following call panics, it indicates UnimplementedAdsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdsService_ServiceDesc, srv)
}

func _AdsService_GetAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdsService_GetAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetAd(ctx, req.(*GetAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_CreateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).CreateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdsService_CreateAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).CreateAd(ctx, req.(*CreateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_UpdateAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).UpdateAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdsService_UpdateAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).UpdateAnalysis(ctx, req.(*UpdateAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdsService_GetSimilarAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimilarAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdsServiceServer).GetSimilarAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdsService_GetSimilarAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdsServiceServer).GetSimilarAds(ctx, req.(*GetSimilarAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdsService_ServiceDesc is the grpc.ServiceDesc for AdsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ads.v1.AdsService",
	HandlerType: (*AdsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAd",
			Handler:    _AdsService_GetAd_Handler,
		},
		{
			MethodName: "CreateAd",
			Handler:    _AdsService_CreateAd_Handler,
		},
		{
			MethodName: "UpdateAnalysis",
			Handler:    _AdsService_UpdateAnalysis_Handler,
		},
		{
			MethodName: "GetSimilarAds",
			Handler:    _AdsService_GetSimilarAds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ads/v1/ads.proto",
}
